### ISSUE TITLE
`to` instead of `endpointId` in the example's messages.send parameters

### ISSUE THREAD

**Issue by sallespro** [respoke/node-respoke-admin#9]
hey, i just noticed this message parameters in the example.
```
             billy.messages.send({
                 to: 'superWombat',
                 message: 'Hi wombat'
             });
```

instead of
```
```
             billy.messages.send({
                 endpointId: 'superWombat',
                 message: 'Hi wombat'
             });
```

**Comment by chadxz** [comment]
Thanks for the heads up @sallespro !
